### ISSUE TITLE
Update status colors from Aaron

### ISSUE THREAD

**Issue by stdavis** [agrc/wri-web#62]
Make sure that we are using these colors:
```css
#projectStatus-Draft {background:#838e8e;} /* Draft - Gray */
#projectStatus-Proposed {background:#000000;} /* Proposed - Black */
#projectStatus-Current {background:#2191AE;} /* Current - Blue */
#projectStatus-PendingCompleted {background:#CC9F2B;} /* Pending-Completed - Yellow */
#projectStatus-Completed {background:#269345;} /* Completed - Green */
#projectStatus-Cancelled {background:#BE1E2D;} /* Cancelled - Red */
```

Confirmed that there is no "new" status.
